export const QUERY_KEY = {
  attendance: 'attendance',
  biometrics: 'biometrics',
  costCenters: 'cost-centers',
  departments: 'departments',
  employees: 'employees',
  hiringTypes: 'hiring-types',
  positions: 'positions',
  requisitions: 'requisitions',
  requisitionStates: 'requisition-states',
  users: 'users',
  vacations: 'vacations',
  vacancies: 'vacancies',
  vacancyStates: 'vacancy-states',
} as const
