/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as PrivateSplatRouteImport } from './routes/_private/$'
import { Route as PrivateVacationsIndexRouteImport } from './routes/_private/vacations/index'
import { Route as PrivateUsersIndexRouteImport } from './routes/_private/users/index'
import { Route as PrivateEmployeesIndexRouteImport } from './routes/_private/employees/index'
import { Route as PrivateBiometricsIndexRouteImport } from './routes/_private/biometrics/index'
import { Route as PrivateAttendanceIndexRouteImport } from './routes/_private/attendance/index'
import { Route as PrivateAdminsIndexRouteImport } from './routes/_private/admins/index'
import { Route as PrivateAboutIndexRouteImport } from './routes/_private/about/index'
import { Route as PublicAuthLoginIndexRouteImport } from './routes/_public/_auth/login/index'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateSplatRoute = PrivateSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateVacationsIndexRoute = PrivateVacationsIndexRouteImport.update({
  id: '/vacations/',
  path: '/vacations/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateUsersIndexRoute = PrivateUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateEmployeesIndexRoute = PrivateEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateBiometricsIndexRoute = PrivateBiometricsIndexRouteImport.update({
  id: '/biometrics/',
  path: '/biometrics/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAttendanceIndexRoute = PrivateAttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAdminsIndexRoute = PrivateAdminsIndexRouteImport.update({
  id: '/admins/',
  path: '/admins/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAboutIndexRoute = PrivateAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PublicAuthLoginIndexRoute = PublicAuthLoginIndexRouteImport.update({
  id: '/_auth/login/',
  path: '/login/',
  getParentRoute: () => PublicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/$': typeof PrivateSplatRoute
  '/about/': typeof PrivateAboutIndexRoute
  '/admins/': typeof PrivateAdminsIndexRoute
  '/attendance/': typeof PrivateAttendanceIndexRoute
  '/biometrics/': typeof PrivateBiometricsIndexRoute
  '/employees/': typeof PrivateEmployeesIndexRoute
  '/users/': typeof PrivateUsersIndexRoute
  '/vacations/': typeof PrivateVacationsIndexRoute
  '/login/': typeof PublicAuthLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute
  '/$': typeof PrivateSplatRoute
  '/about': typeof PrivateAboutIndexRoute
  '/admins': typeof PrivateAdminsIndexRoute
  '/attendance': typeof PrivateAttendanceIndexRoute
  '/biometrics': typeof PrivateBiometricsIndexRoute
  '/employees': typeof PrivateEmployeesIndexRoute
  '/users': typeof PrivateUsersIndexRoute
  '/vacations': typeof PrivateVacationsIndexRoute
  '/login': typeof PublicAuthLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_private/$': typeof PrivateSplatRoute
  '/_private/': typeof PrivateIndexRoute
  '/_private/about/': typeof PrivateAboutIndexRoute
  '/_private/admins/': typeof PrivateAdminsIndexRoute
  '/_private/attendance/': typeof PrivateAttendanceIndexRoute
  '/_private/biometrics/': typeof PrivateBiometricsIndexRoute
  '/_private/employees/': typeof PrivateEmployeesIndexRoute
  '/_private/users/': typeof PrivateUsersIndexRoute
  '/_private/vacations/': typeof PrivateVacationsIndexRoute
  '/_public/_auth/login/': typeof PublicAuthLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about/'
    | '/admins/'
    | '/attendance/'
    | '/biometrics/'
    | '/employees/'
    | '/users/'
    | '/vacations/'
    | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/admins'
    | '/attendance'
    | '/biometrics'
    | '/employees'
    | '/users'
    | '/vacations'
    | '/login'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/$'
    | '/_private/'
    | '/_private/about/'
    | '/_private/admins/'
    | '/_private/attendance/'
    | '/_private/biometrics/'
    | '/_private/employees/'
    | '/_private/users/'
    | '/_private/vacations/'
    | '/_public/_auth/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/$': {
      id: '/_private/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof PrivateSplatRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/vacations/': {
      id: '/_private/vacations/'
      path: '/vacations'
      fullPath: '/vacations/'
      preLoaderRoute: typeof PrivateVacationsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/users/': {
      id: '/_private/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof PrivateUsersIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/employees/': {
      id: '/_private/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof PrivateEmployeesIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/biometrics/': {
      id: '/_private/biometrics/'
      path: '/biometrics'
      fullPath: '/biometrics/'
      preLoaderRoute: typeof PrivateBiometricsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/attendance/': {
      id: '/_private/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof PrivateAttendanceIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/admins/': {
      id: '/_private/admins/'
      path: '/admins'
      fullPath: '/admins/'
      preLoaderRoute: typeof PrivateAdminsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/about/': {
      id: '/_private/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof PrivateAboutIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_public/_auth/login/': {
      id: '/_public/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof PublicAuthLoginIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PrivateRouteRouteChildren {
  PrivateSplatRoute: typeof PrivateSplatRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivateAboutIndexRoute: typeof PrivateAboutIndexRoute
  PrivateAdminsIndexRoute: typeof PrivateAdminsIndexRoute
  PrivateAttendanceIndexRoute: typeof PrivateAttendanceIndexRoute
  PrivateBiometricsIndexRoute: typeof PrivateBiometricsIndexRoute
  PrivateEmployeesIndexRoute: typeof PrivateEmployeesIndexRoute
  PrivateUsersIndexRoute: typeof PrivateUsersIndexRoute
  PrivateVacationsIndexRoute: typeof PrivateVacationsIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateSplatRoute: PrivateSplatRoute,
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateAboutIndexRoute: PrivateAboutIndexRoute,
  PrivateAdminsIndexRoute: PrivateAdminsIndexRoute,
  PrivateAttendanceIndexRoute: PrivateAttendanceIndexRoute,
  PrivateBiometricsIndexRoute: PrivateBiometricsIndexRoute,
  PrivateEmployeesIndexRoute: PrivateEmployeesIndexRoute,
  PrivateUsersIndexRoute: PrivateUsersIndexRoute,
  PrivateVacationsIndexRoute: PrivateVacationsIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAuthLoginIndexRoute: typeof PublicAuthLoginIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAuthLoginIndexRoute: PublicAuthLoginIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
