/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as PrivateSplatRouteImport } from './routes/_private/$'
import { Route as PrivateBiometricsRouteRouteImport } from './routes/_private/biometrics/route'
import { Route as PrivateVacationsIndexRouteImport } from './routes/_private/vacations/index'
import { Route as PrivateVacanciesIndexRouteImport } from './routes/_private/vacancies/index'
import { Route as PrivateUsersIndexRouteImport } from './routes/_private/users/index'
import { Route as PrivateSalaryProcessingIndexRouteImport } from './routes/_private/salary-processing/index'
import { Route as PrivateSalariesIndexRouteImport } from './routes/_private/salaries/index'
import { Route as PrivateRequisitionsIndexRouteImport } from './routes/_private/requisitions/index'
import { Route as PrivatePositionsIndexRouteImport } from './routes/_private/positions/index'
import { Route as PrivatePermissionsIndexRouteImport } from './routes/_private/permissions/index'
import { Route as PrivatePermissionGroupsIndexRouteImport } from './routes/_private/permission-groups/index'
import { Route as PrivateLeavesIndexRouteImport } from './routes/_private/leaves/index'
import { Route as PrivateHiringTypesIndexRouteImport } from './routes/_private/hiring-types/index'
import { Route as PrivateEmployeesIndexRouteImport } from './routes/_private/employees/index'
import { Route as PrivateEmployeeSalariesIndexRouteImport } from './routes/_private/employee-salaries/index'
import { Route as PrivateDepartmentsIndexRouteImport } from './routes/_private/departments/index'
import { Route as PrivateCostCentersIndexRouteImport } from './routes/_private/cost-centers/index'
import { Route as PrivateAttendanceIndexRouteImport } from './routes/_private/attendance/index'
import { Route as PrivateAdminsIndexRouteImport } from './routes/_private/admins/index'
import { Route as PrivateAboutIndexRouteImport } from './routes/_private/about/index'
import { Route as PrivateBiometricsEventsRouteImport } from './routes/_private/biometrics/events'
import { Route as PrivateBiometricsEquipmentsRouteImport } from './routes/_private/biometrics/equipments'
import { Route as PublicAuthLoginIndexRouteImport } from './routes/_public/_auth/login/index'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateSplatRoute = PrivateSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateBiometricsRouteRoute = PrivateBiometricsRouteRouteImport.update({
  id: '/biometrics',
  path: '/biometrics',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateVacationsIndexRoute = PrivateVacationsIndexRouteImport.update({
  id: '/vacations/',
  path: '/vacations/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateVacanciesIndexRoute = PrivateVacanciesIndexRouteImport.update({
  id: '/vacancies/',
  path: '/vacancies/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateUsersIndexRoute = PrivateUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateSalaryProcessingIndexRoute =
  PrivateSalaryProcessingIndexRouteImport.update({
    id: '/salary-processing/',
    path: '/salary-processing/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateSalariesIndexRoute = PrivateSalariesIndexRouteImport.update({
  id: '/salaries/',
  path: '/salaries/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateRequisitionsIndexRoute =
  PrivateRequisitionsIndexRouteImport.update({
    id: '/requisitions/',
    path: '/requisitions/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivatePositionsIndexRoute = PrivatePositionsIndexRouteImport.update({
  id: '/positions/',
  path: '/positions/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivatePermissionsIndexRoute = PrivatePermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivatePermissionGroupsIndexRoute =
  PrivatePermissionGroupsIndexRouteImport.update({
    id: '/permission-groups/',
    path: '/permission-groups/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateLeavesIndexRoute = PrivateLeavesIndexRouteImport.update({
  id: '/leaves/',
  path: '/leaves/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateHiringTypesIndexRoute = PrivateHiringTypesIndexRouteImport.update({
  id: '/hiring-types/',
  path: '/hiring-types/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateEmployeesIndexRoute = PrivateEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateEmployeeSalariesIndexRoute =
  PrivateEmployeeSalariesIndexRouteImport.update({
    id: '/employee-salaries/',
    path: '/employee-salaries/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateDepartmentsIndexRoute = PrivateDepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateCostCentersIndexRoute = PrivateCostCentersIndexRouteImport.update({
  id: '/cost-centers/',
  path: '/cost-centers/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAttendanceIndexRoute = PrivateAttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAdminsIndexRoute = PrivateAdminsIndexRouteImport.update({
  id: '/admins/',
  path: '/admins/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAboutIndexRoute = PrivateAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateBiometricsEventsRoute = PrivateBiometricsEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PrivateBiometricsRouteRoute,
} as any)
const PrivateBiometricsEquipmentsRoute =
  PrivateBiometricsEquipmentsRouteImport.update({
    id: '/equipments',
    path: '/equipments',
    getParentRoute: () => PrivateBiometricsRouteRoute,
  } as any)
const PublicAuthLoginIndexRoute = PublicAuthLoginIndexRouteImport.update({
  id: '/_auth/login/',
  path: '/login/',
  getParentRoute: () => PublicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/biometrics': typeof PrivateBiometricsRouteRouteWithChildren
  '/$': typeof PrivateSplatRoute
  '/biometrics/equipments': typeof PrivateBiometricsEquipmentsRoute
  '/biometrics/events': typeof PrivateBiometricsEventsRoute
  '/about/': typeof PrivateAboutIndexRoute
  '/admins/': typeof PrivateAdminsIndexRoute
  '/attendance/': typeof PrivateAttendanceIndexRoute
  '/cost-centers/': typeof PrivateCostCentersIndexRoute
  '/departments/': typeof PrivateDepartmentsIndexRoute
  '/employee-salaries/': typeof PrivateEmployeeSalariesIndexRoute
  '/employees/': typeof PrivateEmployeesIndexRoute
  '/hiring-types/': typeof PrivateHiringTypesIndexRoute
  '/leaves/': typeof PrivateLeavesIndexRoute
  '/permission-groups/': typeof PrivatePermissionGroupsIndexRoute
  '/permissions/': typeof PrivatePermissionsIndexRoute
  '/positions/': typeof PrivatePositionsIndexRoute
  '/requisitions/': typeof PrivateRequisitionsIndexRoute
  '/salaries/': typeof PrivateSalariesIndexRoute
  '/salary-processing/': typeof PrivateSalaryProcessingIndexRoute
  '/users/': typeof PrivateUsersIndexRoute
  '/vacancies/': typeof PrivateVacanciesIndexRoute
  '/vacations/': typeof PrivateVacationsIndexRoute
  '/login/': typeof PublicAuthLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute
  '/biometrics': typeof PrivateBiometricsRouteRouteWithChildren
  '/$': typeof PrivateSplatRoute
  '/biometrics/equipments': typeof PrivateBiometricsEquipmentsRoute
  '/biometrics/events': typeof PrivateBiometricsEventsRoute
  '/about': typeof PrivateAboutIndexRoute
  '/admins': typeof PrivateAdminsIndexRoute
  '/attendance': typeof PrivateAttendanceIndexRoute
  '/cost-centers': typeof PrivateCostCentersIndexRoute
  '/departments': typeof PrivateDepartmentsIndexRoute
  '/employee-salaries': typeof PrivateEmployeeSalariesIndexRoute
  '/employees': typeof PrivateEmployeesIndexRoute
  '/hiring-types': typeof PrivateHiringTypesIndexRoute
  '/leaves': typeof PrivateLeavesIndexRoute
  '/permission-groups': typeof PrivatePermissionGroupsIndexRoute
  '/permissions': typeof PrivatePermissionsIndexRoute
  '/positions': typeof PrivatePositionsIndexRoute
  '/requisitions': typeof PrivateRequisitionsIndexRoute
  '/salaries': typeof PrivateSalariesIndexRoute
  '/salary-processing': typeof PrivateSalaryProcessingIndexRoute
  '/users': typeof PrivateUsersIndexRoute
  '/vacancies': typeof PrivateVacanciesIndexRoute
  '/vacations': typeof PrivateVacationsIndexRoute
  '/login': typeof PublicAuthLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_private/biometrics': typeof PrivateBiometricsRouteRouteWithChildren
  '/_private/$': typeof PrivateSplatRoute
  '/_private/': typeof PrivateIndexRoute
  '/_private/biometrics/equipments': typeof PrivateBiometricsEquipmentsRoute
  '/_private/biometrics/events': typeof PrivateBiometricsEventsRoute
  '/_private/about/': typeof PrivateAboutIndexRoute
  '/_private/admins/': typeof PrivateAdminsIndexRoute
  '/_private/attendance/': typeof PrivateAttendanceIndexRoute
  '/_private/cost-centers/': typeof PrivateCostCentersIndexRoute
  '/_private/departments/': typeof PrivateDepartmentsIndexRoute
  '/_private/employee-salaries/': typeof PrivateEmployeeSalariesIndexRoute
  '/_private/employees/': typeof PrivateEmployeesIndexRoute
  '/_private/hiring-types/': typeof PrivateHiringTypesIndexRoute
  '/_private/leaves/': typeof PrivateLeavesIndexRoute
  '/_private/permission-groups/': typeof PrivatePermissionGroupsIndexRoute
  '/_private/permissions/': typeof PrivatePermissionsIndexRoute
  '/_private/positions/': typeof PrivatePositionsIndexRoute
  '/_private/requisitions/': typeof PrivateRequisitionsIndexRoute
  '/_private/salaries/': typeof PrivateSalariesIndexRoute
  '/_private/salary-processing/': typeof PrivateSalaryProcessingIndexRoute
  '/_private/users/': typeof PrivateUsersIndexRoute
  '/_private/vacancies/': typeof PrivateVacanciesIndexRoute
  '/_private/vacations/': typeof PrivateVacationsIndexRoute
  '/_public/_auth/login/': typeof PublicAuthLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biometrics'
    | '/$'
    | '/biometrics/equipments'
    | '/biometrics/events'
    | '/about/'
    | '/admins/'
    | '/attendance/'
    | '/cost-centers/'
    | '/departments/'
    | '/employee-salaries/'
    | '/employees/'
    | '/hiring-types/'
    | '/leaves/'
    | '/permission-groups/'
    | '/permissions/'
    | '/positions/'
    | '/requisitions/'
    | '/salaries/'
    | '/salary-processing/'
    | '/users/'
    | '/vacancies/'
    | '/vacations/'
    | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biometrics'
    | '/$'
    | '/biometrics/equipments'
    | '/biometrics/events'
    | '/about'
    | '/admins'
    | '/attendance'
    | '/cost-centers'
    | '/departments'
    | '/employee-salaries'
    | '/employees'
    | '/hiring-types'
    | '/leaves'
    | '/permission-groups'
    | '/permissions'
    | '/positions'
    | '/requisitions'
    | '/salaries'
    | '/salary-processing'
    | '/users'
    | '/vacancies'
    | '/vacations'
    | '/login'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/biometrics'
    | '/_private/$'
    | '/_private/'
    | '/_private/biometrics/equipments'
    | '/_private/biometrics/events'
    | '/_private/about/'
    | '/_private/admins/'
    | '/_private/attendance/'
    | '/_private/cost-centers/'
    | '/_private/departments/'
    | '/_private/employee-salaries/'
    | '/_private/employees/'
    | '/_private/hiring-types/'
    | '/_private/leaves/'
    | '/_private/permission-groups/'
    | '/_private/permissions/'
    | '/_private/positions/'
    | '/_private/requisitions/'
    | '/_private/salaries/'
    | '/_private/salary-processing/'
    | '/_private/users/'
    | '/_private/vacancies/'
    | '/_private/vacations/'
    | '/_public/_auth/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/$': {
      id: '/_private/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof PrivateSplatRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/biometrics': {
      id: '/_private/biometrics'
      path: '/biometrics'
      fullPath: '/biometrics'
      preLoaderRoute: typeof PrivateBiometricsRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/vacations/': {
      id: '/_private/vacations/'
      path: '/vacations'
      fullPath: '/vacations/'
      preLoaderRoute: typeof PrivateVacationsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/vacancies/': {
      id: '/_private/vacancies/'
      path: '/vacancies'
      fullPath: '/vacancies/'
      preLoaderRoute: typeof PrivateVacanciesIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/users/': {
      id: '/_private/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof PrivateUsersIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/salary-processing/': {
      id: '/_private/salary-processing/'
      path: '/salary-processing'
      fullPath: '/salary-processing/'
      preLoaderRoute: typeof PrivateSalaryProcessingIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/salaries/': {
      id: '/_private/salaries/'
      path: '/salaries'
      fullPath: '/salaries/'
      preLoaderRoute: typeof PrivateSalariesIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/requisitions/': {
      id: '/_private/requisitions/'
      path: '/requisitions'
      fullPath: '/requisitions/'
      preLoaderRoute: typeof PrivateRequisitionsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/positions/': {
      id: '/_private/positions/'
      path: '/positions'
      fullPath: '/positions/'
      preLoaderRoute: typeof PrivatePositionsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/permissions/': {
      id: '/_private/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof PrivatePermissionsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/permission-groups/': {
      id: '/_private/permission-groups/'
      path: '/permission-groups'
      fullPath: '/permission-groups/'
      preLoaderRoute: typeof PrivatePermissionGroupsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/leaves/': {
      id: '/_private/leaves/'
      path: '/leaves'
      fullPath: '/leaves/'
      preLoaderRoute: typeof PrivateLeavesIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/hiring-types/': {
      id: '/_private/hiring-types/'
      path: '/hiring-types'
      fullPath: '/hiring-types/'
      preLoaderRoute: typeof PrivateHiringTypesIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/employees/': {
      id: '/_private/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof PrivateEmployeesIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/employee-salaries/': {
      id: '/_private/employee-salaries/'
      path: '/employee-salaries'
      fullPath: '/employee-salaries/'
      preLoaderRoute: typeof PrivateEmployeeSalariesIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/departments/': {
      id: '/_private/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof PrivateDepartmentsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/cost-centers/': {
      id: '/_private/cost-centers/'
      path: '/cost-centers'
      fullPath: '/cost-centers/'
      preLoaderRoute: typeof PrivateCostCentersIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/attendance/': {
      id: '/_private/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof PrivateAttendanceIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/admins/': {
      id: '/_private/admins/'
      path: '/admins'
      fullPath: '/admins/'
      preLoaderRoute: typeof PrivateAdminsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/about/': {
      id: '/_private/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof PrivateAboutIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/biometrics/events': {
      id: '/_private/biometrics/events'
      path: '/events'
      fullPath: '/biometrics/events'
      preLoaderRoute: typeof PrivateBiometricsEventsRouteImport
      parentRoute: typeof PrivateBiometricsRouteRoute
    }
    '/_private/biometrics/equipments': {
      id: '/_private/biometrics/equipments'
      path: '/equipments'
      fullPath: '/biometrics/equipments'
      preLoaderRoute: typeof PrivateBiometricsEquipmentsRouteImport
      parentRoute: typeof PrivateBiometricsRouteRoute
    }
    '/_public/_auth/login/': {
      id: '/_public/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof PublicAuthLoginIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PrivateBiometricsRouteRouteChildren {
  PrivateBiometricsEquipmentsRoute: typeof PrivateBiometricsEquipmentsRoute
  PrivateBiometricsEventsRoute: typeof PrivateBiometricsEventsRoute
}

const PrivateBiometricsRouteRouteChildren: PrivateBiometricsRouteRouteChildren =
  {
    PrivateBiometricsEquipmentsRoute: PrivateBiometricsEquipmentsRoute,
    PrivateBiometricsEventsRoute: PrivateBiometricsEventsRoute,
  }

const PrivateBiometricsRouteRouteWithChildren =
  PrivateBiometricsRouteRoute._addFileChildren(
    PrivateBiometricsRouteRouteChildren,
  )

interface PrivateRouteRouteChildren {
  PrivateBiometricsRouteRoute: typeof PrivateBiometricsRouteRouteWithChildren
  PrivateSplatRoute: typeof PrivateSplatRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivateAboutIndexRoute: typeof PrivateAboutIndexRoute
  PrivateAdminsIndexRoute: typeof PrivateAdminsIndexRoute
  PrivateAttendanceIndexRoute: typeof PrivateAttendanceIndexRoute
  PrivateCostCentersIndexRoute: typeof PrivateCostCentersIndexRoute
  PrivateDepartmentsIndexRoute: typeof PrivateDepartmentsIndexRoute
  PrivateEmployeeSalariesIndexRoute: typeof PrivateEmployeeSalariesIndexRoute
  PrivateEmployeesIndexRoute: typeof PrivateEmployeesIndexRoute
  PrivateHiringTypesIndexRoute: typeof PrivateHiringTypesIndexRoute
  PrivateLeavesIndexRoute: typeof PrivateLeavesIndexRoute
  PrivatePermissionGroupsIndexRoute: typeof PrivatePermissionGroupsIndexRoute
  PrivatePermissionsIndexRoute: typeof PrivatePermissionsIndexRoute
  PrivatePositionsIndexRoute: typeof PrivatePositionsIndexRoute
  PrivateRequisitionsIndexRoute: typeof PrivateRequisitionsIndexRoute
  PrivateSalariesIndexRoute: typeof PrivateSalariesIndexRoute
  PrivateSalaryProcessingIndexRoute: typeof PrivateSalaryProcessingIndexRoute
  PrivateUsersIndexRoute: typeof PrivateUsersIndexRoute
  PrivateVacanciesIndexRoute: typeof PrivateVacanciesIndexRoute
  PrivateVacationsIndexRoute: typeof PrivateVacationsIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateBiometricsRouteRoute: PrivateBiometricsRouteRouteWithChildren,
  PrivateSplatRoute: PrivateSplatRoute,
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateAboutIndexRoute: PrivateAboutIndexRoute,
  PrivateAdminsIndexRoute: PrivateAdminsIndexRoute,
  PrivateAttendanceIndexRoute: PrivateAttendanceIndexRoute,
  PrivateCostCentersIndexRoute: PrivateCostCentersIndexRoute,
  PrivateDepartmentsIndexRoute: PrivateDepartmentsIndexRoute,
  PrivateEmployeeSalariesIndexRoute: PrivateEmployeeSalariesIndexRoute,
  PrivateEmployeesIndexRoute: PrivateEmployeesIndexRoute,
  PrivateHiringTypesIndexRoute: PrivateHiringTypesIndexRoute,
  PrivateLeavesIndexRoute: PrivateLeavesIndexRoute,
  PrivatePermissionGroupsIndexRoute: PrivatePermissionGroupsIndexRoute,
  PrivatePermissionsIndexRoute: PrivatePermissionsIndexRoute,
  PrivatePositionsIndexRoute: PrivatePositionsIndexRoute,
  PrivateRequisitionsIndexRoute: PrivateRequisitionsIndexRoute,
  PrivateSalariesIndexRoute: PrivateSalariesIndexRoute,
  PrivateSalaryProcessingIndexRoute: PrivateSalaryProcessingIndexRoute,
  PrivateUsersIndexRoute: PrivateUsersIndexRoute,
  PrivateVacanciesIndexRoute: PrivateVacanciesIndexRoute,
  PrivateVacationsIndexRoute: PrivateVacationsIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAuthLoginIndexRoute: typeof PublicAuthLoginIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAuthLoginIndexRoute: PublicAuthLoginIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
