/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as PrivateSplatRouteImport } from './routes/_private/$'
import { Route as PrivateEmployeesIndexRouteImport } from './routes/_private/employees/index'
import { Route as PrivateAdminsIndexRouteImport } from './routes/_private/admins/index'
import { Route as PrivateAboutIndexRouteImport } from './routes/_private/about/index'

const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateSplatRoute = PrivateSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateEmployeesIndexRoute = PrivateEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAdminsIndexRoute = PrivateAdminsIndexRouteImport.update({
  id: '/admins/',
  path: '/admins/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAboutIndexRoute = PrivateAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => PrivateRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/$': typeof PrivateSplatRoute
  '/about/': typeof PrivateAboutIndexRoute
  '/admins/': typeof PrivateAdminsIndexRoute
  '/employees/': typeof PrivateEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof PrivateSplatRoute
  '/': typeof PrivateIndexRoute
  '/about': typeof PrivateAboutIndexRoute
  '/admins': typeof PrivateAdminsIndexRoute
  '/employees': typeof PrivateEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_private/$': typeof PrivateSplatRoute
  '/_private/': typeof PrivateIndexRoute
  '/_private/about/': typeof PrivateAboutIndexRoute
  '/_private/admins/': typeof PrivateAdminsIndexRoute
  '/_private/employees/': typeof PrivateEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/about/' | '/admins/' | '/employees/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/' | '/about' | '/admins' | '/employees'
  id:
    | '__root__'
    | '/_private'
    | '/_private/$'
    | '/_private/'
    | '/_private/about/'
    | '/_private/admins/'
    | '/_private/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/$': {
      id: '/_private/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof PrivateSplatRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/employees/': {
      id: '/_private/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof PrivateEmployeesIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/admins/': {
      id: '/_private/admins/'
      path: '/admins'
      fullPath: '/admins/'
      preLoaderRoute: typeof PrivateAdminsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/about/': {
      id: '/_private/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof PrivateAboutIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
  }
}

interface PrivateRouteRouteChildren {
  PrivateSplatRoute: typeof PrivateSplatRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivateAboutIndexRoute: typeof PrivateAboutIndexRoute
  PrivateAdminsIndexRoute: typeof PrivateAdminsIndexRoute
  PrivateEmployeesIndexRoute: typeof PrivateEmployeesIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateSplatRoute: PrivateSplatRoute,
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateAboutIndexRoute: PrivateAboutIndexRoute,
  PrivateAdminsIndexRoute: PrivateAdminsIndexRoute,
  PrivateEmployeesIndexRoute: PrivateEmployeesIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
